### ISSUE TITLE
Combine JWT and Cookie APIs

### ISSUE THREAD

**Issue by VictorioBerra** [damienbod/AspNetCoreExperiments#22]
Isn't one of the major benefits of using a SPA/Blazor WASM is that you consume the same API as everyone else?

Wouldn't this lead to lots of code duplication? IE: `ProductController.cs`, `JwtProductController.cs`?

I think it would be smart if you could use the same controller for JWT and Cookie, and toggle the Antiforgery requirement on and off depending on the caller.

In reference to: https://github.com/damienbod/AspNetCoreExperiments/blob/main/BlazorBffAzureADWithApi/Server/Controllers/MyApiJwtProtectedController.cs

**Comment by damienbod** [comment]
@VictorioBerra I like to keep these separate endpoints (not the implementation) 

This makes it easy to explain and add to the security context diagrams. 

But being simple in small projects I sometimes put them together

Greetings Damien
